import { ReactNode } from "react";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import bannerImg from "@/public/banner.png";
import styles from "@/styles/Layout.module.css";
import AccountBadge from "./account-badge";

type Props = {
  children?: ReactNode;
};

export default function Layout({ children }: Props) {
  return (
    <>
      <Head>
        <title>Real-PET</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.banner}>
        <Image
          src={bannerImg}
          alt=""
          width={bannerImg.width * 2}
          height={bannerImg.height * 2}
          quality={100}
        />
      </div>

      <div className={styles.layout}>
        <div className={styles.navbar}>
          <div className={styles.links}>
            <Link href="/">Home</Link>
            <Link href="/">Mods</Link>
            <Link href="/">Servers</Link>
          </div>

          <AccountBadge />
        </div>
        <main className={styles.main}>{children}</main>
      </div>
    </>
  );
}
